# Generated by Django 2.0.1 on 2018-05-06 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id_produto', models.IntegerField(editable=False, primary_key=True, serialize=False)),
                ('descricao', models.CharField(max_length=50)),
                ('preco_custo', models.DecimalField(decimal_places=2, max_digits=8)),
                ('preco_venda', models.DecimalField(decimal_places=2, max_digits=8)),
                ('observacao', models.TextField()),
                ('data_criacao', models.DateField(auto_now_add=True)),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='imagens_produto')),
            ],
            options={
                'db_table': 'produto',
            },
        ),
    ]
