# Generated by Django 2.0.1 on 2018-05-08 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='observacao',
            field=models.TextField(blank=True, null=True),
        ),
    ]
