# Generated by Django 2.0.1 on 2018-05-09 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0002_auto_20180508_1400'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='id_produto',
            field=models.AutoField(editable=False, primary_key=True, serialize=False),
        ),
    ]
